### PR TITLE
Add github CI workflow

### PR DESCRIPTION
**Pull request by matthiasbeyer**
I am not sure about the required libraries. There's possibly some `apt-get install` stuff missing here.

Please also note that the "CI" job is there for accumulation of matrix-jobs, which would be required if you plan to implement for example [bors](https://bors.tech).
If not, it can be removed of course.

Tell me what you'd like to have.

### CODE REVIEW

**Comment by nik012003** [comment]
Thank you so much!
We definately need these packages to build it:
`sudo apt install libgtk-4-dev build-essential`
It would be awsome if on every github release, it would automatically build and upload it to cargo.io

For now that's all we need. Later, we would need to automatically package it to deb,rpm and possibly Appimage. 
Windows and macOs builds should teorically also be possible, as I used cross-platform frameworks, but I can't figure out how to compile it on windows.

**Comment by matthiasbeyer** [comment]
So I cannot help with auto-release (never did this) and not with non-linux builds.

Also, I do not know where e2d0b1a comes from, I did not add is to this PR!

**Comment by matthiasbeyer** [comment]
Ah, it seems you rebased. Do never rebase public history!

**Comment by nik012003** [comment]
Yeah, sorry I needed to remove .gif file :disappointed:

**Pull request merged**
